spring.application.name=cafeteria

n8n.webhook.url=http://localhost:5678/webhook/pergunta
n8n.webhook.timeout-ms=30000

app.cors.allowed-origin=http://localhost:5173/

logging.level.com.chatbot.backend=INFO
logging.level.org.springframework.web=INFO
